### ISSUE TITLE
API Starts before DB is ready

### ISSUE THREAD

**Issue by alex-stout** [UWEC-ITC/parkingNotifier#3]
**Describe the bug**
When running docker-compose the API starts up and tries to connect to mongoDB before mongoDB is ready to accept a connection.

**To Reproduce**
1. `docker-compose build`
2. `docker-compose up`

**Expected behavior**
The API should wait to connect or at least retry a few times to give MongoDB enough chance to startup.

**Error Output**

> > parking-api           | API listening on port  9000
> parking-api           | { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
> parking-api           |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:564:11)
> parking-api           |     at Pool.emit (events.js:182:13)
> parking-api           |     at Connection.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:317:12)
> parking-api           |     at Object.onceWrapper (events.js:273:13)
> parking-api           |     at Connection.emit (events.js:182:13)
> parking-api           |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:246:50)
> parking-api           |     at Object.onceWrapper (events.js:273:13)
> parking-api           |     at Socket.emit (events.js:182:13)
> parking-api           |     at emitErrorNT (internal/streams/destroy.js:82:8)
> parking-api           |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
> parking-api           |     at process._tickCallback (internal/process/next_tick.js:63:19)
> parking-api           |   name: 'MongoNetworkError',
> parking-api           |   errorLabels: [ 'TransientTransactionError' ],
> parking-api           |   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by alex-stout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix problem when API starts up and DB isn't ready](https://trello.com/c/2QdkjJRx/39-fix-problem-when-api-starts-up-and-db-isnt-ready)

**Comment by alex-stout** [comment]
Should be fixed as of commit 21970b9887d9330cbc9b8fb5d713a13924ccbeda.
Steps used to fix:

- Added 20 second delay into the connection of the database
- Fixed the networking between the two containers. Localhost references the container that it's in. That was the problem.
